# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', model_utils.fields.StatusField(choices=[('add_story', 'add_story'), ('add_comment', 'add_comment'), ('add_comment_reply', 'add_comment_reply'), ('used_tool', 'used_tool')], default='add_story', max_length=100, no_check_for_status=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
