# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180209_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='tool_or_story_id',
            field=models.IntegerField(default=0),
        ),
    ]
