# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityentry_tool_or_story_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='hashtag',
            field=models.CharField(default='', max_length=12),
        ),
    ]
