# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activityentry_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentry',
            name='hashtag',
            field=models.CharField(default='', max_length=25),
        ),
    ]
