# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 10:27
from __future__ import unicode_literals

from django.db import migrations
import re

def rebuild_activity_links(apps, schema_editor): 
    ActivityEntry = apps.get_model('activities', 'ActivityEntry')
    tool_activities = ActivityEntry.objects.filter(reverse_url__iregex=r'tools/\d+')
    story_activities = ActivityEntry.objects.filter(reverse_url__iregex=r'tools/story/\d+')

    for tool_activity in tool_activities: 
        hashtag = re.findall(r'#comment-+\d', tool_activity.reverse_url)
        if len(hashtag) == 0: 
            hashtag = ''
        else:
            hashtag = hashtag[0]
        reverse_url = 'tools:show'  # +re.sub(r'#[a-z,0-9,-]+$','', tool_activity.link)
        tool_id = re.findall(r'\d+', tool_activity.reverse_url)[0]
        tool_activity.hashtag = hashtag
        tool_activity.reverse_url =reverse_url
        tool_activity.tool_or_story_id = tool_id
        tool_activity.save()

    for story_activity in story_activities: 
        reverse_url = 'tools:show_story'
        hashtag = re.findall(r'#comment-+\d', story_activity.reverse_url)
        if len(hashtag) == 0: 
            hashtag = ''
        else:
            hashtag = hashtag[0]
        story_id = re.findall(r'\d+', story_activity.reverse_url)[0]
        story_activity.hashtag = hashtag
        story_activity.tool_or_story_id = story_id
        story_activity.reverse_url = reverse_url
        story_activity.save()
         
class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20180209_1041'),
    ]

    operations = [
        migrations.RunPython(rebuild_activity_links)
    ]

