# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_aactivityentry_rebuild_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityentry',
            old_name='tool_or_story_id',
            new_name='related_id',
        ),
    ]
