# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 21:41
from __future__ import unicode_literals

from django.db import migrations
from django.urls import reverse

def link_to_reverse_url(apps, schema_editor): 
    ActivityEntry = apps.get_model('activities', 'ActivityEntry')
    for entry in ActivityEntry.objects.all(): 
        link = '{}{}'.format(reverse(entry.reverse_url, args=[entry.related_id]), entry.hashtag)
        entry.reverse_url = link
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20180209_2109'),
    ]

    operations = [
        migrations.RunPython(link_to_reverse_url)
    ]
