# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20180209_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityentry',
            old_name='reverse_url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='activityentry',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='activityentry',
            name='related_id',
        ),
    ]
