# Generated by Django 2.2.3 on 2019-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Start date and time')),
                ('end_datetime', models.DateTimeField(verbose_name='End date and time')),
                ('event_type', models.CharField(choices=[('Event', 0), ('Workshop', 1)], default=0, max_length=20, verbose_name='Event type')),
                ('title', models.CharField(help_text='Give Your Event a name.', max_length=150, verbose_name='Event Title')),
                ('description', models.TextField(help_text='Describe your Event here.', max_length=2000, verbose_name='Event Description')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL for Event')),
            ],
            options={
                'verbose_name': 'Events And Workshops',
            },
        ),
    ]
