# Generated by Django 2.2.3 on 2019-10-09 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventworkshop',
            name='participiants',
            field=models.ManyToManyField(null=True, related_name='participiants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventworkshop',
            name='event_type',
            field=models.CharField(choices=[(0, 'Event'), (1, 'Workshop')], default=0, max_length=20, verbose_name='Event type'),
        ),
        migrations.CreateModel(
            name='EventFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_notify', models.BooleanField(default=False)),
                ('event_workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='events_workshops.EventWorkshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
