# Generated by Django 2.2.3 on 2019-10-09 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_workshops', '0002_auto_20191009_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventworkshop',
            name='participiants',
            field=models.ManyToManyField(related_name='participiants', to=settings.AUTH_USER_MODEL),
        ),
    ]
