# Generated by Django 2.2.3 on 2019-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_workshops', '0003_auto_20191009_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventworkshop',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Event'), (1, 'Workshop')], default=0, verbose_name='Event type'),
        ),
    ]
