# Generated by Django 2.2.3 on 2019-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_workshops', '0004_auto_20191009_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventworkshop',
            options={'verbose_name': 'Event Or Workshop', 'verbose_name_plural': 'Events And Workshops'},
        ),
        migrations.AddField(
            model_name='eventworkshop',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
