# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_object_id', models.PositiveIntegerField()),
                ('tree_id', models.IntegerField(db_index=True, null=True)),
                ('content', models.TextField(max_length=5000)),
                ('added_dt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('edited_dt', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.ThreadedComment')),
                ('related_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['tree_id', 'added_dt'],
            },
        ),
    ]
