# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180116_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
