# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadedcomment',
            name='comment_root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.CommentRoot'),
        ),
    ]
