# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20190723_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadedcomment',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='threadedcomment',
            name='related_object_type',
        ),
    ]
