# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0002_auto_20190725_1043'),
        ('comments', '0006_auto_20190723_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadedcomment',
            name='notification_target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_notifications.NotificationTarget'),
        ),
    ]
