# Generated by Django 2.2.3 on 2019-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=50, null=True, verbose_name='Headline')),
                ('subtext', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtext')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
