# Generated by Django 2.2.3 on 2019-10-02 12:07

from django.db import migrations


def create_default_footer(apps, schema_editor): 
    Footer = apps.get_model("pages", "FooterTextblock")
    footer = Footer()
    footer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_footertextblock'),
    ]

    operations = [
        migrations.RunPython(create_default_footer)
    ]
