# Generated by Django 2.2.3 on 2019-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_make_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBarInfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Looking for a specific tool?', max_length=50, verbose_name='Headline')),
                ('body', models.TextField(default='Search within all tools and stories of change here', max_length=200, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Search Bar Info Text',
            },
        ),
        migrations.AlterModelOptions(
            name='footertextblock',
            options={'verbose_name': 'Footer Contact Text Block'},
        ),
    ]
