# Generated by Django 2.2.3 on 2019-10-02 12:31

from django.db import migrations


def create_default_searchtext(apps, schema_editor):
    SearchText = apps.get_model("pages", "SearchBarInfoText")
    text = SearchText()
    text.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191002_1231'),
    ]

    operations = [
        migrations.RunPython(create_default_searchtext),
    ]
