# Generated by Django 2.2.3 on 2019-10-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_make_default_searchtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchbarinfotext',
            name='with_highlight',
            field=models.BooleanField(default=True, help_text='When checked, the first word of the body texty will be red', verbose_name='Use Highlight'),
        ),
    ]
