# Generated by Django 2.2.8 on 2020-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200316_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashtextnew',
            options={'ordering': ['order'], 'verbose_name': 'Flash Text', 'verbose_name_plural': 'Flash Texts'},
        ),
        migrations.AddField(
            model_name='flashtextnew',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
