# Generated by Django 2.2.8 on 2020-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200320_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashtextnew',
            name='subtext',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Subtext'),
        ),
    ]
