# Generated by Django 2.2.8 on 2020-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200320_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertextblock',
            name='body',
            field=models.TextField(default='To get in touch with the team behind Reflection Action, drop us an e-mail at: ', max_length=200, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='footertextblock',
            name='contact_mail',
            field=models.EmailField(default='reflectionaction@ms.dk', max_length=254, verbose_name='Contact address'),
        ),
    ]
