# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('menu', models.CharField(choices=[('footer-1', 'Networked Toolbox'), ('footer-2', 'The Network'), ('footer-3', 'The Toolbox')], default='footer-1', max_length=20)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='pages.Page')),
            ],
        ),
    ]
