# Generated by Django 2.2.8 on 2020-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.CharField(choices=[('footer-1', 'Reflection Action'), ('footer-2', 'The Network'), ('footer-3', 'The Toolbox')], default='footer-1', max_length=20),
        ),
    ]
