# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('main_text', models.TextField(blank=True, default='Lorem ipsum.', max_length=5000, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='published')),
            ],
            options={
                'verbose_name': 'Thematic Area',
                'verbose_name_plural': 'Thematic Areas',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_notify', models.BooleanField(default=False)),
                ('category_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tools.CategoryGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "'Thematic Area Follower",
                'verbose_name_plural': 'Thematic Area Followers',
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupOverviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Lorem ipsum.', max_length=100)),
                ('description', models.CharField(default='Lorem ipsum.', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image)),
                ('link', models.CharField(default='Loren ipsum.', max_length=160)),
                ('link_text', models.CharField(default='Lorem ipsum.', max_length=40)),
            ],
            options={
                'verbose_name': 'Thematic Areas Overview Page',
            },
        ),
        migrations.CreateModel(
            name='CategoryOverviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Lorem ipsum.', max_length=100)),
                ('description', models.CharField(default='Lorem ipsum.', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image)),
                ('link', models.CharField(default='Loren ipsum.', max_length=160)),
                ('link_text', models.CharField(default='Lorem ipsum.', max_length=40)),
            ],
            options={
                'verbose_name': 'Toolboxes Overview Page',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=20000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Story',
                'ordering': ('created',),
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='StoryOverviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Lorem ipsum.', max_length=100)),
                ('description', models.CharField(default='Lorem ipsum.', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image)),
                ('link', models.CharField(default='Loren ipsum.', max_length=160)),
                ('link_text', models.CharField(default='Lorem ipsum.', max_length=40)),
            ],
            options={
                'verbose_name': 'Stories Overview Page',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000)),
                ('attachement', models.FileField(blank=True, null=True, upload_to=tools.models.do_upload_suggestion_attachement)),
                ('related_object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=20000)),
                ('resources_text', models.CharField(blank=True, default='Here you can find the different resources related to the current tool.', max_length=300)),
                ('published', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'ordering': ['title'],
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=20000)),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resources_text', models.CharField(blank=True, default='Here you can find the different resources related to the current category.', max_length=300)),
                ('group', models.ForeignKey(default=tools.models.get_default_category_group_id, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categories', related_query_name='category', to='tools.CategoryGroup')),
            ],
            options={
                'verbose_name': 'Toolbox',
                'ordering': ['order', 'group'],
                'verbose_name_plural': 'Toolboxes',
            },
        ),
        migrations.CreateModel(
            name='ToolFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_notify', models.BooleanField(default=False)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "'Tool Follower",
                'verbose_name_plural': 'Tool Followers',
            },
        ),
        migrations.CreateModel(
            name='ToolOverviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Lorem ipsum.', max_length=100)),
                ('description', models.CharField(default='Lorem ipsum.', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image)),
                ('link', models.CharField(default='Loren ipsum.', max_length=160)),
                ('link_text', models.CharField(default='Lorem ipsum.', max_length=40)),
            ],
            options={
                'verbose_name': 'Tools Overview Page',
            },
        ),
        migrations.CreateModel(
            name='ToolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_notify', models.BooleanField(default=False)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool User',
                'verbose_name_plural': 'Tool Users',
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='categories',
            field=models.ManyToManyField(related_name='tools', related_query_name='tool', to='tools.ToolCategory', verbose_name='toolboxes'),
        ),
        migrations.AddField(
            model_name='story',
            name='associated_tools',
            field=models.ManyToManyField(blank=True, related_name='associated_tools', to='tools.Tool'),
        ),
        migrations.AddField(
            model_name='story',
            name='category_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='tools.CategoryGroup', verbose_name='Thematic Area'),
        ),
        migrations.AddField(
            model_name='story',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='tools.Tool'),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterUniqueTogether(
            name='tooluser',
            unique_together=set([('user', 'tool')]),
        ),
        migrations.AlterUniqueTogether(
            name='toolfollower',
            unique_together=set([('user', 'tool')]),
        ),
        migrations.AlterUniqueTogether(
            name='categorygroupfollower',
            unique_together=set([('user', 'category_group')]),
        ),
    ]
