# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Lorem ipsum.', max_length=255)),
            ],
            options={
                'verbose_name': 'Section Headline',
                'verbose_name_plural': 'Section Headlines',
            },
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='headline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.SectionHeadline'),
        ),
        migrations.AddField(
            model_name='story',
            name='headline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.SectionHeadline'),
        ),
        migrations.AddField(
            model_name='tool',
            name='headline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.SectionHeadline'),
        ),
    ]
