# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20171212_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryOverviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Lorem ipsum.', max_length=100)),
                ('description', models.CharField(default='Lorem ipsum.', max_length=255)),
            ],
            options={
                'verbose_name': 'Stories Overview Page',
            },
        ),
        migrations.AlterModelOptions(
            name='categorygroupoverviewpage',
            options={'verbose_name': 'Work Areas Overview Page'},
        ),
        migrations.AlterModelOptions(
            name='categoryoverviewpage',
            options={'verbose_name': 'Toolboxes Overview Page'},
        ),
        migrations.AlterModelOptions(
            name='tooloverviewpage',
            options={'verbose_name': 'Tools Overview Page'},
        ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='headline',
            field=models.CharField(default='Lorem ipsum.', max_length=100),
        ),
        migrations.AddField(
            model_name='categoryoverviewpage',
            name='headline',
            field=models.CharField(default='Lorem ipsum.', max_length=100),
        ),
        migrations.AddField(
            model_name='tooloverviewpage',
            name='headline',
            field=models.CharField(default='Lorem ipsum.', max_length=100),
        ),
    ]
