# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20171212_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image),
        ),
        migrations.AddField(
            model_name='categoryoverviewpage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image),
        ),
        migrations.AddField(
            model_name='storyoverviewpage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image),
        ),
        migrations.AddField(
            model_name='tooloverviewpage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image),
        ),
    ]
