# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20171213_1304'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='categorygroupoverviewpage',
        #     name='link',
        #     field=models.CharField(default='Loren ipsum.', max_length=60),
        # ),
      
    ]
