# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_auto_20171213_1404'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='categorygroupoverviewpage',
        #     name='link',
        #     field=models.CharField(default='Loren ipsum.', max_length=160),
        # ),
        migrations.AlterField(
            model_name='categoryoverviewpage',
            name='link',
            field=models.CharField(default='Loren ipsum.', max_length=160),
        ),
        migrations.AlterField(
            model_name='storyoverviewpage',
            name='link',
            field=models.CharField(default='Loren ipsum.', max_length=160),
        ),
        migrations.AlterField(
            model_name='tooloverviewpage',
            name='link',
            field=models.CharField(default='Loren ipsum.', max_length=160),
        ),
    ]
