# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20171213_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='link_text',
            field=models.CharField(default='Lorem ipsum.', max_length=40),
        ),
        migrations.AddField(
            model_name='categoryoverviewpage',
            name='link_text',
            field=models.CharField(default='Lorem ipsum.', max_length=40),
        ),
        migrations.AddField(
            model_name='storyoverviewpage',
            name='link_text',
            field=models.CharField(default='Lorem ipsum.', max_length=40),
        ),
        migrations.AddField(
            model_name='tooloverviewpage',
            name='link_text',
            field=models.CharField(default='Lorem ipsum.', max_length=40),
        ),
    ]
