# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0012_auto_20171214_0959'),
    ]

    operations = [
        
        migrations.AlterUniqueTogether(
            name='categorygroupfollower',
            unique_together=set([('user', 'category_group')]),
        ),
    ]
