# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0012_auto_20171214_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroupFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_notify', models.BooleanField(default=False)),
                ('category_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tools.CategoryGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "'Work Area Follower",
                'verbose_name_plural': 'Work Area Followers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='categorygroupfollower',
            unique_together=set([('user', 'category_group')]),
        ),
    ]
