# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0013_auto_20180110_1328'),
    ]

    operations = [
       
       
        migrations.AlterUniqueTogether(
            name='tooluser',
            unique_together=set([('user', 'tool')]),
        ),
    ]
