# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0013_auto_20180110_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tools.Tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tool Users',
                'verbose_name': 'Tool User',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterUniqueTogether(
            name='tooluser',
            unique_together=set([('user', 'tool')]),
        ),
    ]
