# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20180112_1429'),
    ]

    