# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 23:01
from __future__ import unicode_literals

from django.db import migrations


def move_rows(apps, schema_editor): 
    ToolUser = apps.get_model('tools', 'ToolUser')
    ToolFollower = apps.get_model('tools', 'ToolFollower')
    for follower in ToolFollower.objects.all().values(): 
        ToolUser.objects.create(**follower)

class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_tooluser_should_notify'),
    ]

    operations = [
        migrations.RunPython(move_rows),
    ]
