# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_auto_20180204_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='associated_tools',
            field=models.ManyToManyField(blank=True, related_name='associated_tools', to='tools.Tool'),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=20000),
        ),
    ]
