# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_auto_20180206_1419'),
    ]

    operations = [
      
    ]
