# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_auto_20180206_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroupOverviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Lorem ipsum.', max_length=255)),
            ],
            options={
                'verbose_name': 'Work Area Overview Page',
            },
        ),

        migrations.AlterModelOptions(
            name='categorygroupoverviewpage',
            options={'verbose_name': 'Work Areas Overview Page'},
        ),
        # migrations.RemoveField(
        #     model_name='story',
        #     name='category_group',
        # ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image),
        ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='headline',
            field=models.CharField(default='Lorem ipsum.', max_length=100),
        ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='link',
            field=models.CharField(default='Loren ipsum.', max_length=160),
        ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='link_text',
            field=models.CharField(default='Lorem ipsum.', max_length=40),
        ),
    ]
