# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0021_auto_20180208_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='tools.CategoryGroup', verbose_name='work area'),
        ),
    ]
