# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_story_category_group'),
    ]

   