# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0023_auto_20180208_1524'),
    ]

    operations = [
        
        
    ]
