# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 15:32
from __future__ import unicode_literals

from django.db import migrations


def publish(apps, schema_editor): 
    work_areas = apps.get_model('tools', 'CategoryGroup')
    stories = apps.get_model('tools', 'Story')
    work_areas.objects.all().update(published=True)
    stories.objects.all().update(published=True)

def create_overviews(apps, schema_editor): 
    work_area_overview = apps.get_model('tools', 'CategoryGroupOverviewPage')
    tool_overview = apps.get_model('tools', 'ToolOverviewPage')
    story_overview = apps.get_model('tools', 'StoryOverviewPage')
    
    work_area_overview.objects.all().delete()
    tool_overview.objects.all().delete()
    story_overview.objects.all().delete()
    story_overview.objects.create(**
        {
            'id':1,
            'headline':'Stories on how methods and tools are used in action.', 
            'link': 'tools:show_all_stories', 
            'link_text':'Get Inspired'
            }
        )
    tool_overview.objects.create(**
        {
            'id':1, 
            'headline':'Tools for participation, ready to take in the field.',
            'description': 'In this section you can browse through the many tools and processes in the toolbox. To see tools sorted by categories, go to the Categories section.',  
            'link': 'tools:list_tools', 
            'link_text':'Find The Right Tool.'
            }
        )
    work_area_overview.objects.create(**
        {
            'id':1, 
            'headline':'Our best practice about participatory action.',
            'link': 'tools:index', 
            'link_text':'Explore Work Areas.'
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_auto_20180208_1526'),
    ]

    operations = [
        migrations.RunPython(publish), 
        migrations.RunPython(create_overviews)
    ]
