# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0025_auto_20180208_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='related_to_tool',
            field=models.IntegerField(default=0),
        ),
    ]
