# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 22:33
from __future__ import unicode_literals

from django.db import migrations

def gather_tool_ids(apps, schema_editor): 
    Story = apps.get_model('tools', 'Story')
    for story in Story.objects.all(): 
        if story.tool: 
            story.related_to_tool = story.tool.id
            story.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0026_story_related_to_tool'),
    ]

    operations = [
        migrations.RunPython(gather_tool_ids)
    ]
