# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0028_remove_story_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='tools.Tool'),
        ),
    ]
