# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 22:38
from __future__ import unicode_literals

from django.db import migrations

def connect_story_and_tool(apps, schema_editor):
    Story = apps.get_model('tools', 'Story')
    Tool = apps.get_model('tools', 'Tool')
    for story in Story.objects.all(): 
        if story.related_to_tool != 0: 
            story.tool = Tool.objects.get(id=story.related_to_tool)
            story.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0029_story_tool'),
    ]

    operations = [
        migrations.RunPython(connect_story_and_tool)
    ]
