# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0030_auto_20180209_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='related_to_tool',
        ),
    ]
