# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_commentroot'),
        ('tools', '0031_remove_story_related_to_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='comment_root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.CommentRoot'),
        ),
        migrations.AddField(
            model_name='tool',
            name='comment_root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.CommentRoot'),
        ),
    ]
