# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 16:21
from __future__ import unicode_literals
from django.apps import apps
from django.db import migrations
from django.db.models import Q


def create_new_resource_connection(apps, schema_editor):
    from toolz.curried import pipe, map
    from toolz import curry

    @curry
    def create_connection_instance(model_class, obj):
        connection = model_class.objects.create()
        obj.resource_connection = connection
        obj.save()
        return obj

    @curry
    def link_resources(obj):
        
        connection = obj.resource_connection
        ToolResource = apps.get_model('resources', 'ToolResource')
        ContentType = apps.get_model('contenttypes', 'ContentType')
        ctype = ContentType.objects.get_for_model(obj).id
        resources = ToolResource.objects.filter(
            Q(content_type=ctype)& 
            Q(object_id=obj.id)
        )
        resources.update(resource_connection=connection)
        return obj

    ResourceConnection = apps.get_model('resources', 'ToolResourceConnection')
    Toolbox = apps.get_model('tools', 'ToolCategory')
    Tool = apps.get_model('tools', 'Tool')
    tools = Tool.objects.all()
    toolboxes = Toolbox.objects.all()
    modified_toolboxes = pipe(
        map(create_connection_instance(ResourceConnection), toolboxes),
        map(link_resources),
        list
    )
    modified_tools = pipe(
        map(create_connection_instance(ResourceConnection), tools),
        map(link_resources),
        list
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0034_auto_20190723_1621'),
    ]

    operations = [
        migrations.RunPython(create_new_resource_connection)
    ]
