# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0038_auto_20190723_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='tools.SuggestionRoot'),
        ),
        migrations.AddField(
            model_name='tool',
            name='suggestion_root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.SuggestionRoot'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='suggestion_root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.SuggestionRoot'),
        ),
    ]
