# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 16:21
from __future__ import unicode_literals
from django.apps import apps
from django.db import migrations
from django.db.models import Q


def create_new_suggestion_root(apps, schema_editor):
    from toolz.curried import pipe, map
    from toolz import curry

    @curry
    def create_instance(model_class, obj):
        suggestion_root = model_class.objects.create()
        obj.suggestion_root = suggestion_root
        obj.save()
        return obj

    @curry
    def link_resources(obj):

        suggestion_root = obj.suggestion_root
        Suggestion = apps.get_model('tools', 'Suggestion')
        ContentType = apps.get_model('contenttypes', 'ContentType')
        ctype = ContentType.objects.get_for_model(obj).id
        suggestions = Suggestion.objects.filter(
            Q(related_content_type=ctype) &
            Q(related_object_id=obj.id)
        )
        suggestions.update(suggestion_root=suggestion_root)
        return obj

    SuggestionRoot = apps.get_model('tools', 'SuggestionRoot')
    Toolbox = apps.get_model('tools', 'ToolCategory')
    Tool = apps.get_model('tools', 'Tool')
    tools = Tool.objects.all()
    toolboxes = Toolbox.objects.all()
    modified_toolboxes = pipe(
        map(create_instance(SuggestionRoot), toolboxes),
        map(link_resources),
        list
    )
    modified_tools = pipe(
        map(create_instance(SuggestionRoot), tools),
        map(link_resources),
        list
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0039_auto_20190723_2030'),
    ]

    operations = [
        migrations.RunPython(create_new_suggestion_root)
    ]
