# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-23 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0040_connect_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='related_content_type',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='related_object_id',
        ),
    ]
