# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 10:49
from __future__ import unicode_literals
from django.apps import apps
from django.db import migrations


class Migration(migrations.Migration):

    def create_notification_targets(apps, schema_editor): 
        
        def create_notifiaction_target(obj): 
            Target = apps.get_model('user_notifications', 'NotificationTarget')
            target = Target.objects.create()
            obj.notification_target = target
            obj.save()
            return obj 

        Story = apps.get_model('tools', 'Story')
        Tool = apps.get_model('tools', 'Tool')
        WorkArea = apps.get_model('tools', 'CategoryGroup')

        stories = list(map(create_notifiaction_target, Story.objects.all()))
        tools = list(map(create_notifiaction_target, Tool.objects.all()))
        work_areas = list(map(create_notifiaction_target, WorkArea.objects.all()))

    dependencies = [
        ('tools', '0042_auto_20190725_1048'),
    ]

    operations = [
        migrations.RunPython(create_notification_targets)
    ]
