# Generated by Django 2.2.3 on 2019-09-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0044_toolcategory_resource_connection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'verbose_name': 'Thematic Area', 'verbose_name_plural': 'Thematic Areas'},
        ),
        migrations.AlterModelOptions(
            name='categorygroupoverviewpage',
            options={'verbose_name': 'Thematic Areas Overview Page'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('created',), 'verbose_name': 'Story Of Change', 'verbose_name_plural': 'Stories Of Change'},
        ),
        migrations.AlterModelOptions(
            name='storyoverviewpage',
            options={'verbose_name': 'Stories Of Change Overview Page'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['title'], 'verbose_name': 'Tool or Method', 'verbose_name_plural': 'Tools and Methods'},
        ),
        migrations.AlterModelOptions(
            name='tooloverviewpage',
            options={'verbose_name': 'Tools And Methods Overview Page'},
        ),
    ]
