# Generated by Django 2.2.3 on 2019-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0045_auto_20190926_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroupoverviewpage',
            name='description',
            field=models.TextField(default='Lorem ipsum.', max_length=2000, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='categoryoverviewpage',
            name='description',
            field=models.TextField(default='Lorem ipsum.', max_length=2000, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='storyoverviewpage',
            name='description',
            field=models.TextField(default='Lorem ipsum.', max_length=2000, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='tooloverviewpage',
            name='description',
            field=models.TextField(default='Lorem ipsum.', max_length=2000, verbose_name='Explanation'),
        ),
    ]
