# Generated by Django 2.2.8 on 2020-09-29 11:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0046_auto_20191003_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
