# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroupFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_notify', models.BooleanField(default=False)),
                ('category_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tools.CategoryGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work Area Followers',
                'verbose_name': "'Work Area Follower",
            },
        ),
        migrations.CreateModel(
            name='StoryOverviewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Lorem ipsum.', max_length=100)),
                ('description', models.CharField(default='Lorem ipsum.', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image)),
                ('link', models.CharField(default='Loren ipsum.', max_length=160)),
                ('link_text', models.CharField(default='Lorem ipsum.', max_length=40)),
            ],
            options={
                'verbose_name': 'Stories Overview Page',
            },
        ),
        migrations.CreateModel(
            name='ToolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_notify', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tool Users',
                'verbose_name': 'Tool User',
            },
        ),
        migrations.AlterModelOptions(
            name='categorygroupoverviewpage',
            options={'verbose_name': 'Work Areas Overview Page'},
        ),
        migrations.AlterModelOptions(
            name='categoryoverviewpage',
            options={'verbose_name': 'Toolboxes Overview Page'},
        ),
        migrations.AlterModelOptions(
            name='tooloverviewpage',
            options={'verbose_name': 'Tools Overview Page'},
        ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image),
        ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='headline',
            field=models.CharField(default='Lorem ipsum.', max_length=100),
        ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='link',
            field=models.CharField(default='Loren ipsum.', max_length=160),
        ),
        migrations.AddField(
            model_name='categorygroupoverviewpage',
            name='link_text',
            field=models.CharField(default='Lorem ipsum.', max_length=40),
        ),
        migrations.AddField(
            model_name='categoryoverviewpage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image),
        ),
        migrations.AddField(
            model_name='categoryoverviewpage',
            name='headline',
            field=models.CharField(default='Lorem ipsum.', max_length=100),
        ),
        migrations.AddField(
            model_name='categoryoverviewpage',
            name='link',
            field=models.CharField(default='Loren ipsum.', max_length=160),
        ),
        migrations.AddField(
            model_name='categoryoverviewpage',
            name='link_text',
            field=models.CharField(default='Lorem ipsum.', max_length=40),
        ),
        migrations.AddField(
            model_name='story',
            name='associated_tools',
            field=models.ManyToManyField(blank=True, related_name='associated_tools', to='tools.Tool'),
        ),
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='tool',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tooloverviewpage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tools.models.do_upload_cover_image),
        ),
        migrations.AddField(
            model_name='tooloverviewpage',
            name='headline',
            field=models.CharField(default='Lorem ipsum.', max_length=100),
        ),
        migrations.AddField(
            model_name='tooloverviewpage',
            name='link',
            field=models.CharField(default='Loren ipsum.', max_length=160),
        ),
        migrations.AddField(
            model_name='tooloverviewpage',
            name='link_text',
            field=models.CharField(default='Lorem ipsum.', max_length=40),
        ),
        migrations.AlterField(
            model_name='story',
            name='category_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='tools.CategoryGroup', verbose_name='work area'),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='categories',
            field=models.ManyToManyField(related_name='tools', related_query_name='tool', to='tools.ToolCategory', verbose_name='toolboxes'),
        ),
        migrations.AddField(
            model_name='tooluser',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tools.Tool'),
        ),
        migrations.AddField(
            model_name='tooluser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tooluser',
            unique_together=set([('user', 'tool')]),
        ),
        migrations.AlterUniqueTogether(
            name='categorygroupfollower',
            unique_together=set([('user', 'category_group')]),
        ),
    ]
